### ISSUE TITLE
Semi-transparent sliders not working on Linux 

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2053]
Filters work but the sliders appear when Sine is loaded

**Comment by baconpaul** [comment]
PR #2057 improves this a lot but there's still one bug. If you drag a slider handle over a dark image with transparency on it mis-draws the drag handle on the dark sliders

The reason is something (who knows what but something for sure!) is going wrong at the `cairo_paint_with_alpha` call in that case in `cairodrawcontext.cpp` in vstgui land

So to close this either (1) patch VSTgui or (2) set transparency to 1.0 when you are dragging in CSurgeSlider on linux :)

**Comment by tank-trax** [comment]
let me know when you have a fix and will test it

**Comment by baconpaul** [comment]
I may just do the 'linux is opaque when you move it' thing and then see if anything else breaks. Will poke now.

**Comment by baconpaul** [comment]
OK let me know how it works at master! Thanks.

**Comment by tank-trax** [comment]
I was at 415357c and it looks good for Low and High Cut as well as FM Depth and Feedback

noticed some recent changes, going to take a look at c88548a and let u know in a bit

**Comment by K0rrid0r** [comment]
does the same happen on linux as in #2056 @tank-trax ?

**Comment by tank-trax** [comment]
it was better before, now there is no option to Activate via RMB

also the Buttons may ghost

![Screenshot_20200607_203517](https://user-images.githubusercontent.com/41337033/83983727-ca744b00-a8fe-11ea-9459-76097f267881.png)

**Comment by baconpaul** [comment]
Sigh ok I will look tomorrow 
Korridor this is a totally different issue than 2056

**Comment by tank-trax** [comment]
Everything works at  415357c

**Comment by baconpaul** [comment]
No blackout when you drag a transparent fm depth at that revision? I get handles vanishing at that commit

**Comment by tank-trax** [comment]
if transparency in Linux poses a problem would it be possible to have the knob/buttons completely hidden (with just an inactive slider showing) for Low/High Cut, FM Depth and Feedback when they are not active and only have the knobs appear when they are active?

**Comment by VincyZed** [comment]
This is what we were leaning towards before transparency, but this causes problems regarding automation (I think), @K0rrid0r can explain the issue he had with that approach.

**Comment by K0rrid0r** [comment]
I am first of all against the whole idea of hiding sliders just because they are not in a 'on' state. I may be voted down on that but my argument to keep them on all the time or at least transparent when off is that if you hide them when they are in the off state you have no chance to "plan" on what to do with them before you put them on, think in a live situation or recording/jamming live situation where you want to plan things before you turn them on, hiding them completely takes that ability away which is say the least unfair to your potential volume/sound you're working on. Because putting them in the 'on' state may change the sound a lot, especially the FM sliders.

Also potentially fast automation on FM routing and Filter routing (when it finally works if this is kept) will cause blinking of the sliders from off and on state when you maybe need to se clearly what is going on, here maybe a transparent solution would be good after all. But yeah Linux seems a bit hairy on that.

**Comment by baconpaul** [comment]
I pushed exactly that for Linux for now @tank-trax

**Comment by baconpaul** [comment]
Oh jeez more accurately I coded that, put in the PR, let it build, and forgot to press merge!

Pressing merge now. Doh!

**Comment by tank-trax** [comment]
The sliders are active even though the buttons do not show (so for those Linux users the chance to 'plan' where they will be upon activation still exists)

**Comment by baconpaul** [comment]
ha yeah. that's bug-like result of how i did it i guess. but I think for now we will leave it like this on linux until we get the bigger fix after 1.7. Thanks for testing!

**Comment by baconpaul** [comment]
Ahh this works perfectly in juce. Changing the guard from if LINUX to if LINUX & ! TARGET_JUCE_UI and will push and close this.
