### ISSUE TITLE
1.7.0: Build fails: error: expression result unused

### ISSUE THREAD

**Issue by yurivict** [surge-synthesizer/surge#2386]
```
/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.7.0/src/lv2/SurgeLv2Export.cpp:158:15: error: expression result unused [-Werror,-Wunused-value]
              "    lv2:extensionData ui:idleInterface .\n";
              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

clang-9
FreeBSD 12.1

**Comment by baconpaul** [comment]
I'll set up a linux clang build in our pipeline and fix the errors. That will be more efficient than you opening a ticket for each build error :)

**Comment by yurivict** [comment]
No clang fails again:
```
error: unknown warning option '-Wno-implicit-int-float-conversion'; did you mean '-Wno-implicit-float-conversion'? [-Werror,-Wunknown-warning-option]
```

**Comment by baconpaul** [comment]
At 9b8b0663d1 I did two things

1: fixed this bug
2: enabled ubuntu 20 with clang 10 as one of our PR build checks

so you should be good to go on freebsd going forward.

Thanks for your patience and reports.

**Comment by baconpaul** [comment]
Sigh. Clang 9 has a different warning set than Clang 10 11 and 12 it seems. 

https://clang.llvm.org/docs/DiagnosticsReference.html#wimplicit-int-float-conversion

Any ideas how one would work around that in cmake?

**Comment by baconpaul** [comment]
I guess the obvious way is fix the code that is giving that warning :) 

Stand by.

**Comment by yurivict** [comment]
```
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang")

  if (CMAKE_CXX_COMPILER_VERSION ...)
  endif()

endif ()
```

**Comment by baconpaul** [comment]
Yeah thanks! I decided to just put the casts in for explicitness. Will update this when I push.

**Comment by baconpaul** [comment]
OK b9525a7 builds with just -Werror clang10

can you give it a whirl in your environment?

**Comment by baconpaul** [comment]
@yurivict my bet is we push these sets of fixes (not just here but also several other ones we found post release) into a 1.7.1 release late this weekend or early next week. Do you think you would have a chance that you can build the main branch in your environment before we do the tag?

Thanks!

**Comment by yurivict** [comment]
The current ```master``` fails to build:
```
/usr/ports/audio/surge-synthesizer-lv2/work/surge-release_1.7.0-14-g539c1f36/src/common/ImportFilesystem.h:16:35: error: 'filesystem' is deprecated: std::experimental::filesystem has now been deprecated in favor of C++17's std::filesystem. Please stop using it and start using std::filesystem. This experimental version will be removed in LLVM 11. You can remove this warning by defining the _LIBCPP_NO_EXPERIMENTAL_DEPRECATION_WARNING_FILESYSTEM macro. [-Werror,-Wdeprecated-declarations]
namespace fs = std::experimental::filesystem;
                                  ^
/usr/include/c++/v1/experimental/filesystem:246:1: note: 'filesystem' has been explicitly marked deprecated here
_LIBCPP_BEGIN_NAMESPACE_EXPERIMENTAL_FILESYSTEM
^
/usr/include/c++/v1/experimental/__config:46:63: note: expanded from macro '_LIBCPP_BEGIN_NAMESPACE_EXPERIMENTAL_FILESYSTEM'
    _LIBCPP_BEGIN_NAMESPACE_EXPERIMENTAL namespace filesystem _LIBCPP_DEPRECATED_EXPERIMENTAL_FILESYSTEM { \
                                                              ^
/usr/include/c++/v1/experimental/__config:42:70: note: expanded from macro '_LIBCPP_DEPRECATED_EXPERIMENTAL_FILESYSTEM'
#   define _LIBCPP_DEPRECATED_EXPERIMENTAL_FILESYSTEM __attribute__((deprecated("std::experimental::filesystem has now been deprecated in favor of C++17's std::filesystem. Please stop using it and start using std::filesystem. This experimental version will be removed in LLVM 11. You can remove this warning by defining the _LIBCPP_NO_EXPERIMENTAL_DEPRECATION_WARNING_FILESYSTEM macro.")))
                                                                     ^
```

**Comment by baconpaul** [comment]
We moved to main 3 months ago - did you pull master or main?

**Comment by baconpaul** [comment]
Also can you share the cmake output also? Cmake will configure the filesystem includes according to your compiler ability to resolve the symbols 

Thanks

**Comment by baconpaul** [comment]
Sigh yeah I see your has 539c1f which is top Of stack

Well I’m at a loss. We use cmake to resolve the symbol. I build ubuntu clang 10 no problem. I think someone running FreeBSD is going to have to dig in and debug why the cmake symbol resolution works but configured incorrectly. :(

**Comment by yurivict** [comment]
I use 1.7.0-14-g539c1f36

Relevant cmake log lines:
```
-- Looking for std::filesystem::path::preferred_separator
-- Looking for std::filesystem::path::preferred_separator - not found
-- Looking for std::experimental::filesystem::path::preferred_separator
-- Looking for std::experimental::filesystem::path::preferred_separator - found
-- Using std::experimental::filesystem
```

**Comment by baconpaul** [comment]
Right so that’s the problem. That test runs and says don’t use std::fs so we don’t. And then it doesn’t compile. Hmmm

**Comment by yurivict** [comment]
I think maybe treating warnings as errors is enabled during build and not during configure.

**Comment by yurivict** [comment]
```
Determining if the std::filesystem::path::preferred_separator exist failed with the following output:
Change Dir: /usr/ports/audio/surge-synthesizer-lv2/work/.build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/local/bin/ninja cmTC_76bbe && [1/2] Building CXX object CMakeFiles/cmTC_76bbe.dir/CheckSymbolExists.cxx.o
FAILED: CMakeFiles/cmTC_76bbe.dir/CheckSymbolExists.cxx.o
/usr/bin/c++    -O2 -pipe -fno-omit-frame-pointer -fstack-protector-strong -fno-strict-aliasing -fno-omit-frame-pointer    -std=c++14 -o CMakeFiles/cmTC_76bbe.dir/CheckSymbolExists.cxx.o -c CheckSymbolExists.cxx
CheckSymbolExists.cxx:7:19: error: no member named 'filesystem' in namespace 'std'; did you mean 'std::__fs::filesystem'?
  return ((int*)(&std::filesystem::path::preferred_separator))[argc];
                  ^~~~~~~~~~~~~~~
                  std::__fs::filesystem
/usr/include/c++/v1/filesystem:259:1: note: 'std::__fs::filesystem' declared here
_LIBCPP_BEGIN_NAMESPACE_FILESYSTEM
^
/usr/include/c++/v1/__config:767:58: note: expanded from macro '_LIBCPP_BEGIN_NAMESPACE_FILESYSTEM'
  _LIBCPP_BEGIN_NAMESPACE_STD namespace __fs { namespace filesystem {
                                                         ^
1 error generated.
ninja: build stopped: subcommand failed.


File /usr/ports/audio/surge-synthesizer-lv2/work/.build/CMakeFiles/CMakeTmp/CheckSymbolExists.cxx:
/* */
#include <filesystem>

int main(int argc, char** argv)
{
  (void)argv;
  return ((int*)(&std::filesystem::path::preferred_separator))[argc];
}
```

**Comment by baconpaul** [comment]
https://github.com/surge-synthesizer/surge/blob/539c1f36a5fac8edf4d6046f1c7cfe94b5b0537c/CMakeLists.txt#L84

There’s the cmake Logic. That works Ubuntu 16-20 with gcc, ubuntu 20 with clang 10, macos clang 11 and a variety of windows builds also. Can you see what’s happening there that is tripping up FreeBSD? Does your clang environment resolve std::filesystem?

Thanks

**Comment by baconpaul** [comment]
Right so that failing is why we use experimental fs

But why doesn’t that build if the check passes? I wonder what flag is getting toggled downstream...

**Comment by baconpaul** [comment]
But we build with 14 on unixes

https://github.com/surge-synthesizer/surge/blob/539c1f36a5fac8edf4d6046f1c7cfe94b5b0537c/CMakeLists.txt#L76

And set the compiler to 14 also.

**Comment by yurivict** [comment]
You need to bump this to c++17, standard only mentions c++17 where features become different.

**Comment by baconpaul** [comment]
I guess that branch could set FreeBSD to 17 along with windows. Can you see if that results in a build that works?

**Comment by baconpaul** [comment]
Right we concluded the same thing

Ok lemme see if I can move the non Mac unixes to 17 and get back to you. (We need to keep Mac at 14 for a comparability reason)

**Comment by yurivict** [comment]
This is clang and STD implementation dependent. FreeBSD's difference is that it uses clang, while other Unixes use gcc. You should go by what standard says.

**Comment by baconpaul** [comment]
And thanks

**Comment by baconpaul** [comment]
Yeah I get that you are on clang; I added a linux clang build to our pipeline last night. Right now we can build on Ubuntu 20 with Clang 10 but agree that it's not working on your env. Lemme try and move all of linux to 17 and push.

**Comment by yurivict** [comment]
This is likely a gcc compiler bug. The correct behavior is to have std::filesystem for >= c++17 and std::experimental::filesystem for < c++17. Apparently compilers that you used aren't standard compliant.

**Comment by yurivict** [comment]
Personally, I just use the highest C++ standard on my projects. This is least likely to cause issues.

**Comment by baconpaul** [comment]
Yeah I had done that with 1.7.0; and then I left behind a chunk of our macOS users. That's why we are at a mix of 14 and 17 now. I chose 14 for linux/freebsd when I pushed mac back (and kept windows at 17) but I'll move linux back and just keep mac at 14. (If you push mac to 17 you have to drop OSes older than 10.12)

**Comment by baconpaul** [comment]
OK i have a push. Can you try at 602263a

I you are interested this build built on the following configurations and chose the following configurations.

Ubuntu 16, dist stock gcc (5.4.0), c++17 - std::experimental::filesystem
Ubuntu 18, dist stock gcc (7.5.0), c++17 - std::experimental::filesystem
Ubuntu 20, dist stock gcc (9.3.0), c++17 - std::filesystem
Ubuntu 20, clang 10.0, c++17 - std::filesystem 
Ubuntu 18, ARM GCC cross compile, c++17 - std::experimental::filesystem

I'm assuming you don't care about the windows and macs. But it seems you are correct that gcc versions shipping with ubuntu 18 and below (earlier than 9.3.0) are not meeting the C++17 standard (which we knew).

**Comment by yurivict** [comment]
602263a builds fine.

But please note that during the configure phase ```c++17``` still isn't being passed to the compiler: see the file CMakeOutput.log

**Comment by baconpaul** [comment]
Thanks. That CxxCheckSymbolExists thing has an odd way of using C++ flags. I see why that's the case. Let me try one more thing, just for cleanliness.

Appreciate the feedback here. Glad it is building.

**Comment by baconpaul** [comment]
In theory, 5270cfb will build still but also send c++17 to the check process.

I'll close this issue tomorrow but if you get a chance to look it would be appreciated.

Thanks for your help. Glad we got building. Will tag 1.7.1 next week.

**Comment by yurivict** [comment]
5270cfb builds fine.

**Comment by baconpaul** [comment]
Thanks
