### ISSUE TITLE
Messages in command line using AudioPluginHost and Jalv.Select

### ISSUE THREAD

**Issue by tank-trax** [surge-synthesizer/surge#2424]
Not sure if this is a Linux issue only but I noticed this after recent changes when using jalv.select

```
jalv.gtk3 https://surge-synthesizer.github.io/lv2/surge  
Plugin:       https://surge-synthesizer.github.io/lv2/surge
UI:           https://surge-synthesizer.github.io/lv2/surge#UI
JACK Name:    Surge
Sample rate:  48000 Hz
Block length: 512 frames
MIDI buffers: 32768 bytes
Comm buffers: 131072 bytes
Update rate:  25.0 Hz

CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00124.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00119.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00119.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00154.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00149.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00148.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00149.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00105.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00158.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00164.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00140.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00112.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00164.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00134.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00162.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00121.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00134.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00145.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00151.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00140.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00132.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusMPE.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverStatusButton.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00136.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00132.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusZoom.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00137.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00148.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00162.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusButton.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00121.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00163.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00102.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusTune.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00162.svg
extension is svg
Loading SVG/bmpTS00153.svg into TEMPOSYNC_HORIZONTAL_OVERLAY
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00153.svg
extension is svg
Loading SVG/bmpTS00157.svg into TEMPOSYNC_VERTICAL_OVERLAY
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00157.svg
extension is svg
Loading SVG/StatusButton.svg into STATUS_BUTTON
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusButton.svg
extension is svg
Loading SVG/StatusMPE.svg into STATUS_MPE
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusMPE.svg
extension is svg
Loading SVG/StatusTune.svg into STATUS_TUNING
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusTune.svg
extension is svg
Loading SVG/StatusZoom.svg into STATUS_ZOOM
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusZoom.svg
extension is svg
```

thought it may have been an LV2 thing but it happens with the VST3 in JUCE's Audio Plugin Host
```
AudioPluginHost     
IPlugFrame is a runloop 0x558b0147c348
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00124.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00119.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00119.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00154.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00149.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00148.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00149.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00105.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00158.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00164.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00161.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00140.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00112.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00164.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00125.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00134.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00162.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00121.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00108.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00134.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00159.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00145.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00151.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00140.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00132.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusMPE.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverStatusButton.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00118.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00123.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00146.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00136.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00132.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00153.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusZoom.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00126.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00137.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00148.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00152.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00157.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00162.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00114.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusButton.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00121.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00163.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00102.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusTune.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00120.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00144.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmp00143.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00160.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hoverOn00122.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/hover00162.svg
extension is svg
Loading SVG/bmpTS00153.svg into TEMPOSYNC_HORIZONTAL_OVERLAY
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00153.svg
extension is svg
Loading SVG/bmpTS00157.svg into TEMPOSYNC_VERTICAL_OVERLAY
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/bmpTS00157.svg
extension is svg
Loading SVG/StatusButton.svg into STATUS_BUTTON
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusButton.svg
extension is svg
Loading SVG/StatusMPE.svg into STATUS_MPE
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusMPE.svg
extension is svg
Loading SVG/StatusTune.svg into STATUS_TUNING
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusTune.svg
extension is svg
Loading SVG/StatusZoom.svg into STATUS_ZOOM
CSB for /home/studio/.local/share/surge/skins/dark-mode.surge-skin//SVG/StatusZoom.svg
extension is svg
```

**Comment by tank-trax** [comment]
sane thing for the Default Skin

```
CSB for /home/studio/.local/share/surge/skins/default.surge-skin//SVG/hover00113.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/default.surge-skin//SVG/hover00151.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/default.surge-skin//SVG/hover00117.svg
extension is svg
CSB for /home/studio/.local/share/surge/skins/default.surge-skin//SVG/hover00123.svg
```

etc.

**Comment by baconpaul** [comment]
Yeah I fixed that this morning in  925cbfe. Sorry about that. You caught the 12 hours where I left it in by accident after I merged PNG!

**Comment by tank-trax** [comment]
still get this for the Dark Skin only (Default Skin no longer reproduces these responses)

```
Loading SVG/bmpTS00153.svg into TEMPOSYNC_HORIZONTAL_OVERLAY
Loading SVG/bmpTS00157.svg into TEMPOSYNC_VERTICAL_OVERLAY
Loading SVG/StatusButton.svg into STATUS_BUTTON
Loading SVG/StatusMPE.svg into STATUS_MPE
Loading SVG/StatusTune.svg into STATUS_TUNING
Loading SVG/StatusZoom.svg into STATUS_ZOOM
```

**Comment by baconpaul** [comment]
Sorry missed that one!
Will merge a fix shortly.
Thanks!
