### ISSUE TITLE
Preset switching bug

### ISSUE THREAD

**Issue by Engylizium** [surge-synthesizer/surge#4029]
**Bug Description:**
Next preset button switches to the next preset twice while playing project. 
This is random behavior with a 90% chance to switch twice 

**Surge Version**
1.8.1.9de9336

Version: VST3 64-bit

**Reproduction Steps:**
1. Launch Cubase
2. Add VST instrument track
3. Play project
4. Switch presets via next/previous buttons in VST

**Expected Behavior:**
Switch to the next preset once

**Screenshots:**
![PYNtVV8pFV](https://user-images.githubusercontent.com/22287855/110117073-70d77900-7dc9-11eb-8bca-5885d9c5951c.gif)

**Computer Information (please complete the following information):**
 - OS: Windows 10
 - Host: Cubase
 - Version: 9.0.40

**Comment by baconpaul** [comment]
Thanks

We’ve been stubbornly chasing variations on this bug for a while and it is a bit better in the nightly, but we can re-review before 1.9 to see if it is any better. It’s also DAW dependent which is driving us a little crazy. (We also hope our summer port to juce will improve this situation).

Appreciate the accurate bug report!

**Comment by Engylizium** [comment]
So I've decided to try different versions and found that 1.7.1.5270cfb don't have this issue. Hope this can lead on potential cause of the bug

**Comment by baconpaul** [comment]
Thanks

171 has other bugs where the patch is loaded on the wrong thread which can crash many daws in a different situation. I think the double-advance is related to that inside the engine, and made some improvements (if you want to try the nightly that would be appreciated too!) but still no total smoking gun.

That said, some things in the nightly are a lot better around patch load.

**Comment by Engylizium** [comment]
Oh, sorry, yes I've tried nightly but forgot to mention it. Same thing, but maybe a little bit stable - like 70% chance to get bug triggered

**Comment by baconpaul** [comment]
Can I ask one more really dumb thing
If you press and hold the preset button does it ever double advance. Like, press, wait one second, release.
Or is it only if you quick press.
I have a theory - not a good theory - but that question would help inform me.
And appreciate the help here. Surge is good because people provide excellent bug reports like this!
Thank you

**Comment by Engylizium** [comment]
I just tried and didn't found any difference in behavior. 
Also found that this bug affects Category buttons and it doesn't simply double-advance, it can jump 1-4 or so presets/categories

**Comment by baconpaul** [comment]
thank you. Very useful. I have an idea. Won't get to it today but will post on this issue when i do.

**Comment by Engylizium** [comment]
Uhh...Sorry to bother you again, but I also decided to pause before switching presets. Apparently while there is any sound coming from Surge, bug will persist.
So this is full report I think:
(No sound) Switch everything normally. (Sound) Switch to next/previous 1-4 patch/category then cancel any sound from Surge.
If it's possible to cancel sounds before doing switching patches, I think it can be solved

**Comment by baconpaul** [comment]
so the aggravating thing is it does cancel sounds before a switch but I think there's an out of order thing between the UI and audio thread which I just haven't caught yet (which makes the UI thread send the 'next patch' message twice also). That's a hard bug to hunt but we will get it i'm sure. Very useful additional color.

**Comment by Brier1104** [comment]
Get the same behavior in Bitwig 3.3.3.  But only on my external Wacom tablet!  The laptop touch pad works fine.  Go figure.

**Comment by VincyZed** [comment]
I can confirm that this also sometimes happen in the latest version of FL Studio.

**Comment by baconpaul** [comment]
If it happened in on Mac in logic it would be fixed by now :)

inhave some ideas though and tagged this into the 19 milestone. It’s gotta be an event synchronization thing like I said 

thanks all!

**Comment by baconpaul** [comment]
Sigh so I'm having the hardest time making my VM have a setup which shows this. And like I said I can't get mac hosts to do it.

I do have one idea. @VincyZed can you try a build with this change applied

```

void SurgeSynthesizer::incrementPatch(bool nextPrev, bool insideCategory)
{
    // Don't increment if we still have an outstanding load
    if(patchid_queue >= 0 ) return;

    int p = storage.patch_list.size();
```

that if there is inserted. Does that make the situation any better? That should in theory avoid a double load but I don't know why it is happening.

**Comment by VincyZed** [comment]
@baconpaul  I will try. I will first make sure I can reproduce the bug since I think it's been a while since it actually did it, at least that's what I remember. Will let you know...

**Comment by baconpaul** [comment]
Just for @Engylizium sake

1. @VincyZed confirmed that fix did fix the problem
2. So he PRed it and we merged it
3. The nightly now has it as will our upcoming 1.9.0 release

**Comment by Engylizium** [comment]
Sorry to disappoint you guys, but bug is still here. Yesterday I wiped my PC to start anew, just now installed Surge 1.9.nightly.44fff03 and bug is real

**Comment by mkruselj** [comment]
Are you 100% sure you're running that nightly? (See About page.)

**Comment by Engylizium** [comment]
Yes I just downloaded nightly and version is from about page
![Untitled](https://user-images.githubusercontent.com/22287855/113476883-e72dd080-9486-11eb-8b7c-2c7fd563399f.jpg)

**Comment by mkruselj** [comment]
Ha. Unsure if there's anything further we can do about it... You might have to check in a couple of months when we will be ported to JUCE framework.

**Comment by baconpaul** [comment]
I actually found it - by doing the juce port - and its a bug in our code which the juce port made very clear for me. There should b ea fix in 1.9.
