### ISSUE TITLE
surge/src/common/CPUFeatures.cpp:37:10: fatal error: cpuid.h: No such file or directory on RPI 400 (5.10.63-v7l ARMv7)history

### ISSUE THREAD

**Issue by th-m-vogel** [surge-synthesizer/surge#5640]
**Bug Description:**
Will not build on ARM7 Raspberry PI 400

**Reproduction Steps:**
cmake -Bbuild -DLINUX_ON_ARM=True
cmake --build build --config Release --target surge-staged-assets

probably something about the ifdef statement about linux and arm surrounding the use of cpuinfo.h and what is detected on my plattform.
#if LINUX && !ARM_NEON
#ifdef __GNUC__
//  GCC Intrinsics
#include <cpuid.h>
...

**Computer Information (please complete the following information):**
 - PI 400
 - Linux raspberrypi 5.10.63-v7l+ #1488 SMP Thu Nov 18 16:15:28 GMT 2021 armv7l GNU/Linux
 - raspios-bullseye-armhf.img

**Comment by baconpaul** [comment]
Oh yeah that's almost definitely my fault from reshuffling the ARM stuff recently. We don't use ARM_NEON the same way. I'll take a look this cycle. thanks.

**Comment by baconpaul** [comment]
@th-m-vogel right now my raspberry pi is powering my Christmas tree (don't ask) so I don't have a compiler on it.

Any chance you can try this patch which should solve the problem? It looks like I only missed the one spot.  If it does we can merge it up no problem.  If you can't try it, i can take my christmas tree offline tomorrow for a bit :)

Thanks for the report!

```
diff --git a/src/common/CPUFeatures.cpp b/src/common/CPUFeatures.cpp
index 622ae260..2b02b0b7 100644
--- a/src/common/CPUFeatures.cpp
+++ b/src/common/CPUFeatures.cpp
@@ -31,7 +31,7 @@
 #include <intrin.h>
 #define cpuid(info, x) __cpuidex(info, x, 0)
 #else
-#if LINUX && !ARM_NEON
+#if LINUX && !defined(__aarch64__)
 #ifdef __GNUC__
 //  GCC Intrinsics
 #include <cpuid.h>
```

**Comment by th-m-vogel** [comment]
Christmas tree is a valid use for a pi ;) ... i will test this

**Comment by th-m-vogel** [comment]
OK, this does not solve. still wants to include cpuid.h. However, as the intention is to skip this blocjk i commented out the complete block for test and i than fails later because 
line 155 - cpuid is not declated

so, there is more about this ... however, for now i was able to build release 1.8.1 ... what is a workaround so far.

**Comment by baconpaul** [comment]
are you on a 64 bit pi or 32?

**Comment by baconpaul** [comment]
(I am thinking that conditionalizing on `__aarch64__` may not be working properly basically)

**Comment by th-m-vogel** [comment]
ARM7l ... that's 32 bit i think

**Comment by baconpaul** [comment]
Right!
So gcc will define (something) on that architecture. Do you happen to know what it is? __arm71__ maybe?

**Comment by baconpaul** [comment]
and yeah i see now
in globals.h we have

```

#if LINUX
#if defined(__aarch64__)
#define ARM_NEON 1
#endif
#endif
```

that defined needs an || for the 32 bit arm target name also.

**Comment by baconpaul** [comment]
Curious if replacing that with

```
#if LINUX
#if defined(__aarch64__) || defined(__arm__)
#define ARM_NEON 1
#endif
#endif
```

fixes it on your system

**Comment by th-m-vogel** [comment]
change in global.h fixed it

**Comment by baconpaul** [comment]
cool
i'll merge it later today or tomorrow and close this issue when i do
thanks for the help!!

**Comment by th-m-vogel** [comment]
thanks for your help
