### ISSUE TITLE
Bug in Logic? 

### ISSUE THREAD

**Issue by dsnelson1990** [surge-synthesizer/surge#7221]
**Bug Description:**
Error while booting up SurgeXT in Logic Pro X 
"An Audio Unit plug-in reported a problem which might cause the system to become unstable. Please quit and restart Logic Pro."

**Surge XT Version**
This information is found on the About screen, which you get to from the bottom right menu.

* Version:
VST plugin 

**Reproduction Steps:**
2. Click on '...'
3. Scroll down to '...'

**Expected Behavior:**
Expected the plugin to boot up but was unable to load the plugin period. 

**Screenshots:**
<img width="1235" alt="Screenshot 2023-09-24 at 12 37 21 PM" src="https://github.com/surge-synthesizer/surge/assets/145924391/ea1095b9-6d19-48d7-8729-6c0f1dabbfe6">Apple M1 Pro
Ventura 13.5 (22G74)

**Comment by baconpaul** [comment]
which version of surge? I have a suspicion there may be a permissions problem which 1.23 can tickle which we have fixed in the nightly.

If you start the application "Console" and go to "Crash Logs" is there anything there related to audio you could share?

Has surge ever worked for you?

**Comment by dsnelson1990** [comment]
Thanks for the quick response 

I am not well versed in code but this is from, what I believe to be, the crash log 
rashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

**Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000017
Exception Codes:       0x0000000000000001, 0x0000000000000017

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [49056]**



I am not sure if I have version 1.23
Is there a download link to the latest version? I can attempt to reinstall

**Comment by baconpaul** [comment]
Yeah that’s the log if you can attach it all that would help greatly

latest stable is here https://surge-synthesizer.github.io/

and development nightly which may solve the problem if thst doesn’t work is here
https://surge-synthesizer.github.io/nightly_XT/

**Comment by dsnelson1990** [comment]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               Surge XT [59537]
Path:                  /Applications/Surge XT.app/Contents/MacOS/Surge XT
Identifier:            org.surge-synth-team.surge-xt
Version:               1.2.3 (1.2.3)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-09-24 21:28:34.2513 -0400
OS Version:            macOS 13.5 (22G74)
Report Version:        12
Anonymous UUID:        82646DFF-A602-87FA-DF38-6E51F6027D4D

Sleep/Wake UUID:       651101C3-092A-48AC-BE25-6AD6FBDE2A6A

Time Awake Since Boot: 1100000 seconds
Time Since Wake:       8610 seconds

System Integrity Protection: enabled

Crashed Thread:        0  JUCE Message Thread  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000017
Exception Codes:       0x0000000000000001, 0x0000000000000017

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [59537]

VM Region Info: 0x17 is not in any region.  Bytes before following region: 105553518919657
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-/rwx SM=NUL  ...(unallocated)

Thread 0 Crashed:: JUCE Message Thread Dispatch queue: com.apple.main-thread
0   libc++.1.dylib                	       0x19a42f9f8 std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&) + 20
1   Surge XT                      	       0x104699594 Surge::Widgets::FxMenu::scanExtraPresets() + 304
2   Surge XT                      	       0x104694260 Surge::Widgets::XMLMenuPopulator::populate() + 84
3   Surge XT                      	       0x104697794 Surge::Widgets::FxMenu::populateForContext(bool) + 168
4   Surge XT                      	       0x104519344 SurgeGUIEditor::layoutComponentForSkin(std::__1::shared_ptr<Surge::GUI::Skin::Control>, long, int, Parameter*, int) + 6816
5   Surge XT                      	       0x1045120ec SurgeGUIEditor::openOrRecreateEditor() + 12048
6   Surge XT                      	       0x10451f068 SurgeGUIEditor::open(void*) + 964
7   Surge XT                      	       0x1044e47cc SurgeSynthEditor::SurgeSynthEditor(SurgeSynthProcessor&) + 2092
8   Surge XT                      	       0x1044ec1ac SurgeSynthProcessor::createEditor() + 36
9   Surge XT                      	       0x104835cd8 juce::AudioProcessor::createEditorIfNeeded() + 96
10  Surge XT                      	       0x1044e17cc juce::StandaloneFilterWindow::MainContentComponent::MainContentComponent(juce::StandaloneFilterWindow&) + 144
11  Surge XT                      	       0x1044dee88 juce::StandaloneFilterWindow::StandaloneFilterWindow(juce::String const&, juce::Colour, juce::PropertySet*, bool, juce::String const&, juce::AudioDeviceManager::AudioDeviceSetup const*, juce::Array<juce::StandalonePluginHolder::PluginInOuts, juce::DummyCriticalSection, 0> const&, bool) + 328
12  Surge XT                      	       0x1044de9c8 juce::StandaloneFilterApp::createWindow() + 140
13  Surge XT                      	       0x1044de75c juce::StandaloneFilterApp::initialise(juce::String const&) + 28
14  Surge XT                      	       0x10474df84 juce::JUCEApplicationBase::initialiseApp() + 104
15  Surge XT                      	       0x10494a99c juce::JUCEApplication::initialiseApp() + 16
16  Surge XT                      	       0x10474dd0c juce::JUCEApplicationBase::main() + 84
17  Surge XT                      	       0x10474dc68 juce::JUCEApplicationBase::main(int, char const**) + 88
18  dyld                          	       0x19a1a7f28 start + 2236

Thread 1:
0   libsystem_pthread.dylib       	       0x19a4fad8c start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	       0x19a4fad8c start_wqthread + 0

Thread 3:
0   libsystem_pthread.dylib       	       0x19a4fad8c start_wqthread + 0

Thread 4:
0   libsystem_pthread.dylib       	       0x19a4fad8c start_wqthread + 0

Thread 5:: caulk.messenger.shared:17
0   libsystem_kernel.dylib        	       0x19a4bfed0 semaphore_wait_trap + 8
1   caulk                         	       0x1a3b3b024 caulk::semaphore::timed_wait(double) + 212
2   caulk                         	       0x1a3b3aed8 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                         	       0x1a3b3abc8 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib       	       0x19a4fffa8 _pthread_start + 148
5   libsystem_pthread.dylib       	       0x19a4fada0 thread_start + 8

Thread 6:: MacBook Pro Speakers
0   libsystem_kernel.dylib        	       0x19a4c3750 __psynch_cvwait + 8
1   libsystem_pthread.dylib       	       0x19a500574 _pthread_cond_wait + 1232
2   libc++.1.dylib                	       0x19a428f84 std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>) + 100
3   Surge XT                      	       0x1047a6858 juce::WaitableEvent::wait(int) const + 152
4   Surge XT                      	       0x104a5b658 juce::CoreAudioClasses::AudioIODeviceCombiner::readInput(juce::AudioBuffer<float>&, int, int) + 468
5   Surge XT                      	       0x104a5a7f0 juce::CoreAudioClasses::AudioIODeviceCombiner::run() + 1080
6   Surge XT                      	       0x1047a750c juce::Thread::threadEntryPoint() + 288
7   Surge XT                      	       0x1047d756c juce::threadEntryProc(void*) + 32
8   libsystem_pthread.dylib       	       0x19a4fffa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x19a4fada0 thread_start + 8

Thread 7:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x19a4bff54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19a4d2280 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19a4c8bb8 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19a4c02d0 mach_msg + 24
4   CoreAudio                     	       0x19c8ec634 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
5   CoreAudio                     	       0x19c7d9d24 HALC_ProxyIOContext::IOWorkLoop() + 3516
6   CoreAudio                     	       0x19c7d888c invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 116
7   CoreAudio                     	       0x19c93b574 HALB_IOThread::Entry(void*) + 88
8   libsystem_pthread.dylib       	       0x19a4fffa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x19a4fada0 thread_start + 8

Thread 8:: com.apple.audio.IOThread.client
0   libsystem_kernel.dylib        	       0x19a4bff54 mach_msg2_trap + 8
1   libsystem_kernel.dylib        	       0x19a4d2280 mach_msg2_internal + 80
2   libsystem_kernel.dylib        	       0x19a4c8bb8 mach_msg_overwrite + 604
3   libsystem_kernel.dylib        	       0x19a4c02d0 mach_msg + 24
4   CoreAudio                     	       0x19c8ec634 HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int) + 104
5   CoreAudio                     	       0x19c7d9d24 HALC_ProxyIOContext::IOWorkLoop() + 3516
6   CoreAudio                     	       0x19c7d888c invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int) + 116
7   CoreAudio                     	       0x19c93b574 HALB_IOThread::Entry(void*) + 88
8   libsystem_pthread.dylib       	       0x19a4fffa8 _pthread_start + 148
9   libsystem_pthread.dylib       	       0x19a4fada0 thread_start + 8


Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000600003c37900   x1: 0x0000000000000000   x2: 0x0000000000000001   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000600003e38ff0   x6: 0x000000000000000a   x7: 0x0000000000000001
    x8: 0x0000000000000000   x9: 0x0000000000000103  x10: 0x0000c029b96c0000  x11: 0x0000000000000020
   x12: 0x00000000001ff800  x13: 0x00000000000007fb  x14: 0x00000000828011c9  x15: 0x00000000828011c9
   x16: 0x000000019a42f9e4  x17: 0x0000000000003900  x18: 0x0000000000000000  x19: 0x0000600003c37900
   x20: 0x0000000126e95ea0  x21: 0x0000000157093600  x22: 0x0000000126e95f78  x23: 0x000000016b92a2b0
   x24: 0x0000600003c37900  x25: 0x0000600003276970  x26: 0x000000016b92a278  x27: 0x0000000132071000
   x28: 0x0000000000000000   fp: 0x000000016b92a110   lr: 0x0b69000104699594
    sp: 0x000000016b92a100   pc: 0x000000019a42f9f8 cpsr: 0x80001000
   far: 0x0000000000000017  esr: 0x92000006 (Data Abort) byte read Translation fault

Binary Images:
       0x1044d4000 -        0x10582bfff org.surge-synth-team.surge-xt (1.2.3) <e372b3fd-8854-3bae-9072-5dfa1e010094> /Applications/Surge XT.app/Contents/MacOS/Surge XT
       0x10aa0c000 -        0x10aa17fff libobjc-trampolines.dylib (*) <8e928412-9e96-32d4-b173-d99beb9fed0b> /usr/lib/libobjc-trampolines.dylib
       0x19a416000 -        0x19a4a2ff7 libc++.1.dylib (*) <3ee92404-8fc3-374b-a598-d5c9a8cd64b5> /usr/lib/libc++.1.dylib
       0x19a1a2000 -        0x19a230587 dyld (*) <e7a99595-e0f8-34af-be8b-9347d0d658a4> /usr/lib/dyld
       0x19a4f9000 -        0x19a505fff libsystem_pthread.dylib (*) <1f30fb9a-bdf9-32db-a709-8417666a7e45> /usr/lib/system/libsystem_pthread.dylib
       0x19a4bf000 -        0x19a4f8ff7 libsystem_kernel.dylib (*) <08c5fe2a-b0bf-3ab6-bb42-460c18917d33> /usr/lib/system/libsystem_kernel.dylib
       0x1a3b39000 -        0x1a3b61fff com.apple.audio.caulk (1.0) <94eafeb1-517c-3d98-8d0d-9c350f0eb986> /System/Library/PrivateFrameworks/caulk.framework/Versions/A/caulk
       0x19c5fd000 -        0x19cc90fff com.apple.audio.CoreAudio (5.0) <86c35c01-57f0-3e1a-851e-201b9e4f75f9> /System/Library/Frameworks/CoreAudio.framework/Versions/A/CoreAudio
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)
Writable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Activity Tracing                   256K        1 
ColorSync                          480K       23 
CoreGraphics                        16K        1 
Foundation                          16K        1 
Kernel Alloc Once                   32K        1 
MALLOC                           288.4M       44 
MALLOC guard page                  192K       10 
MALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)
MALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)
STACK GUARD                       56.1M        9 
Stack                             12.2M        9 
VM_ALLOCATE                        176K        4 
VM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)
__AUTH                             901K      212 
__AUTH_CONST                      17.7M      394 
__CTF                               824        1 
__DATA                            28.3M      382 
__DATA_CONST                      18.3M      397 
__DATA_DIRTY                       980K      133 
__FONT_DATA                        2352        1 
__LINKEDIT                       807.3M        3 
__OBJC_RO                         66.4M        1 
__OBJC_RW                         2012K        1 
__TEXT                           396.9M      416 
dyld private memory                272K        2 
mapped file                       65.5M       13 
shared memory                     2896K       14 
===========                     =======  ======= 
TOTAL                              2.9G     2082 
TOTAL, minus reserved VM space     1.7G     2082 



-----------
Full Report
-----------

{"app_name":"Surge XT","timestamp":"2023-09-24 21:28:35.00 -0400","app_version":"1.2.3","slice_uuid":"e372b3fd-8854-3bae-9072-5dfa1e010094","build_version":"1.2.3","platform":1,"bundleID":"org.surge-synth-team.surge-xt","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.5 (22G74)","roots_installed":0,"name":"Surge XT","incident_id":"BB301375-7A2F-47DF-BCEC-7BE053AD3842"}
{
  "uptime" : 1100000,
  "procRole" : "Foreground",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "MacBookPro18,1",
  "coalitionID" : 87728,
  "osVersion" : {
    "train" : "macOS 13.5",
    "build" : "22G74",
    "releaseType" : "User"
  },
  "captureTime" : "2023-09-24 21:28:34.2513 -0400",
  "incident" : "BB301375-7A2F-47DF-BCEC-7BE053AD3842",
  "pid" : 59537,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-09-24 21:28:33.4061 -0400",
  "procStartAbsTime" : 28569051276681,
  "procExitAbsTime" : 28569071113573,
  "procName" : "Surge XT",
  "procPath" : "\/Applications\/Surge XT.app\/Contents\/MacOS\/Surge XT",
  "bundleInfo" : {"CFBundleShortVersionString":"1.2.3","CFBundleVersion":"1.2.3","CFBundleIdentifier":"org.surge-synth-team.surge-xt"},
  "storeInfo" : {"deviceIdentifierForVendor":"EFCB44A3-E557-5077-B17E-9895D040FB54","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "org.surge-synth-team.surge-xt",
  "crashReporterKey" : "82646DFF-A602-87FA-DF38-6E51F6027D4D",
  "codeSigningID" : "org.surge-synth-team.surge-xt",
  "codeSigningTeamID" : "G4Y62M4JQ6",
  "codeSigningFlags" : 570499857,
  "codeSigningValidationCategory" : 6,
  "codeSigningTrustLevel" : 0,
  "wakeTime" : 8610,
  "sleepWakeUUID" : "651101C3-092A-48AC-BE25-6AD6FBDE2A6A",
  "sip" : "enabled",
  "vmRegionInfo" : "0x17 is not in any region.  Bytes before following region: 105553518919657\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)",
  "exception" : {"codes":"0x0000000000000001, 0x0000000000000017","rawCodes":[1,23],"type":"EXC_BAD_ACCESS","signal":"SIGSEGV","subtype":"KERN_INVALID_ADDRESS at 0x0000000000000017"},
  "termination" : {"flags":0,"code":11,"namespace":"SIGNAL","indicator":"Segmentation fault: 11","byProc":"exc handler","byPid":59537},
  "vmregioninfo" : "0x17 is not in any region.  Bytes before following region: 105553518919657\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  \n      MALLOC_NANO (reserved)   600018000000-600020000000 [128.0M] rw-\/rwx SM=NUL  ...(unallocated)",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":21454265,"threadState":{"x":[{"value":105553179408640},{"value":0},{"value":1},{"value":0},{"value":0},{"value":105553181511664},{"value":10},{"value":1},{"value":0},{"value":259},{"value":211285437054976},{"value":32},{"value":2095104},{"value":2043},{"value":2189431241},{"value":2189431241},{"value":6883047908,"symbolLocation":0,"symbol":"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)"},{"value":14592},{"value":0},{"value":105553179408640},{"value":4947795616},{"value":5755188736},{"value":4947795832},{"value":6099739312},{"value":105553179408640},{"value":105553169181040},{"value":6099739256},{"value":5134290944},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":822188411340821908},"cpsr":{"value":2147487744},"fp":{"value":6099738896},"sp":{"value":6099738880},"esr":{"value":2449473542,"description":"(Data Abort) byte read Translation fault"},"pc":{"value":6883047928,"matchesCrashFrame":1},"far":{"value":23}},"name":"JUCE Message Thread","queue":"com.apple.main-thread","frames":[{"imageOffset":104952,"symbol":"std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>::basic_string(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>> const&)","symbolLocation":20,"imageIndex":2},{"imageOffset":1856916,"symbol":"Surge::Widgets::FxMenu::scanExtraPresets()","symbolLocation":304,"imageIndex":0},{"imageOffset":1835616,"symbol":"Surge::Widgets::XMLMenuPopulator::populate()","symbolLocation":84,"imageIndex":0},{"imageOffset":1849236,"symbol":"Surge::Widgets::FxMenu::populateForContext(bool)","symbolLocation":168,"imageIndex":0},{"imageOffset":283460,"symbol":"SurgeGUIEditor::layoutComponentForSkin(std::__1::shared_ptr<Surge::GUI::Skin::Control>, long, int, Parameter*, int)","symbolLocation":6816,"imageIndex":0},{"imageOffset":254188,"symbol":"SurgeGUIEditor::openOrRecreateEditor()","symbolLocation":12048,"imageIndex":0},{"imageOffset":307304,"symbol":"SurgeGUIEditor::open(void*)","symbolLocation":964,"imageIndex":0},{"imageOffset":67532,"symbol":"SurgeSynthEditor::SurgeSynthEditor(SurgeSynthProcessor&)","symbolLocation":2092,"imageIndex":0},{"imageOffset":98732,"symbol":"SurgeSynthProcessor::createEditor()","symbolLocation":36,"imageIndex":0},{"imageOffset":3546328,"symbol":"juce::AudioProcessor::createEditorIfNeeded()","symbolLocation":96,"imageIndex":0},{"imageOffset":55244,"symbol":"juce::StandaloneFilterWindow::MainContentComponent::MainContentComponent(juce::StandaloneFilterWindow&)","symbolLocation":144,"imageIndex":0},{"imageOffset":44680,"symbol":"juce::StandaloneFilterWindow::StandaloneFilterWindow(juce::String const&, juce::Colour, juce::PropertySet*, bool, juce::String const&, juce::AudioDeviceManager::AudioDeviceSetup const*, juce::Array<juce::StandalonePluginHolder::PluginInOuts, juce::DummyCriticalSection, 0> const&, bool)","symbolLocation":328,"imageIndex":0},{"imageOffset":43464,"symbol":"juce::StandaloneFilterApp::createWindow()","symbolLocation":140,"imageIndex":0},{"imageOffset":42844,"symbol":"juce::StandaloneFilterApp::initialise(juce::String const&)","symbolLocation":28,"imageIndex":0},{"imageOffset":2596740,"symbol":"juce::JUCEApplicationBase::initialiseApp()","symbolLocation":104,"imageIndex":0},{"imageOffset":4680092,"symbol":"juce::JUCEApplication::initialiseApp()","symbolLocation":16,"imageIndex":0},{"imageOffset":2596108,"symbol":"juce::JUCEApplicationBase::main()","symbolLocation":84,"imageIndex":0},{"imageOffset":2595944,"symbol":"juce::JUCEApplicationBase::main(int, char const**)","symbolLocation":88,"imageIndex":0},{"imageOffset":24360,"symbol":"start","symbolLocation":2236,"imageIndex":3}]},{"id":21454280,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":21454281,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":21454286,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":21454293,"frames":[{"imageOffset":7564,"symbol":"start_wqthread","symbolLocation":0,"imageIndex":4}]},{"id":21454306,"name":"caulk.messenger.shared:17","frames":[{"imageOffset":3792,"symbol":"semaphore_wait_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":8228,"symbol":"caulk::semaphore::timed_wait(double)","symbolLocation":212,"imageIndex":6},{"imageOffset":7896,"symbol":"caulk::concurrent::details::worker_thread::run()","symbolLocation":36,"imageIndex":6},{"imageOffset":7112,"symbol":"void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*)","symbolLocation":96,"imageIndex":6},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]},{"id":21454411,"name":"MacBook Pro Speakers","frames":[{"imageOffset":18256,"symbol":"__psynch_cvwait","symbolLocation":8,"imageIndex":5},{"imageOffset":30068,"symbol":"_pthread_cond_wait","symbolLocation":1232,"imageIndex":4},{"imageOffset":77700,"symbol":"std::__1::condition_variable::__do_timed_wait(std::__1::unique_lock<std::__1::mutex>&, std::__1::chrono::time_point<std::__1::chrono::system_clock, std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l>>>)","symbolLocation":100,"imageIndex":2},{"imageOffset":2959448,"symbol":"juce::WaitableEvent::wait(int) const","symbolLocation":152,"imageIndex":0},{"imageOffset":5797464,"symbol":"juce::CoreAudioClasses::AudioIODeviceCombiner::readInput(juce::AudioBuffer<float>&, int, int)","symbolLocation":468,"imageIndex":0},{"imageOffset":5793776,"symbol":"juce::CoreAudioClasses::AudioIODeviceCombiner::run()","symbolLocation":1080,"imageIndex":0},{"imageOffset":2962700,"symbol":"juce::Thread::threadEntryPoint()","symbolLocation":288,"imageIndex":0},{"imageOffset":3159404,"symbol":"juce::threadEntryProc(void*)","symbolLocation":32,"imageIndex":0},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]},{"id":21454412,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":3924,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":78464,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":5},{"imageOffset":39864,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":5},{"imageOffset":4816,"symbol":"mach_msg","symbolLocation":24,"imageIndex":5},{"imageOffset":3077684,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":104,"imageIndex":7},{"imageOffset":1953060,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3516,"imageIndex":7},{"imageOffset":1947788,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":116,"imageIndex":7},{"imageOffset":3401076,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":7},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]},{"id":21454417,"name":"com.apple.audio.IOThread.client","frames":[{"imageOffset":3924,"symbol":"mach_msg2_trap","symbolLocation":8,"imageIndex":5},{"imageOffset":78464,"symbol":"mach_msg2_internal","symbolLocation":80,"imageIndex":5},{"imageOffset":39864,"symbol":"mach_msg_overwrite","symbolLocation":604,"imageIndex":5},{"imageOffset":4816,"symbol":"mach_msg","symbolLocation":24,"imageIndex":5},{"imageOffset":3077684,"symbol":"HALB_MachPort::SendSimpleMessageWithSimpleReply(unsigned int, unsigned int, int, int&, bool, unsigned int)","symbolLocation":104,"imageIndex":7},{"imageOffset":1953060,"symbol":"HALC_ProxyIOContext::IOWorkLoop()","symbolLocation":3516,"imageIndex":7},{"imageOffset":1947788,"symbol":"invocation function for block in HALC_ProxyIOContext::HALC_ProxyIOContext(unsigned int, unsigned int)","symbolLocation":116,"imageIndex":7},{"imageOffset":3401076,"symbol":"HALB_IOThread::Entry(void*)","symbolLocation":88,"imageIndex":7},{"imageOffset":28584,"symbol":"_pthread_start","symbolLocation":148,"imageIndex":4},{"imageOffset":7584,"symbol":"thread_start","symbolLocation":8,"imageIndex":4}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4367138816,
    "CFBundleShortVersionString" : "1.2.3",
    "CFBundleIdentifier" : "org.surge-synth-team.surge-xt",
    "size" : 20283392,
    "uuid" : "e372b3fd-8854-3bae-9072-5dfa1e010094",
    "path" : "\/Applications\/Surge XT.app\/Contents\/MacOS\/Surge XT",
    "name" : "Surge XT",
    "CFBundleVersion" : "1.2.3"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 4473274368,
    "size" : 49152,
    "uuid" : "8e928412-9e96-32d4-b173-d99beb9fed0b",
    "path" : "\/usr\/lib\/libobjc-trampolines.dylib",
    "name" : "libobjc-trampolines.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6882942976,
    "size" : 577528,
    "uuid" : "3ee92404-8fc3-374b-a598-d5c9a8cd64b5",
    "path" : "\/usr\/lib\/libc++.1.dylib",
    "name" : "libc++.1.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6880370688,
    "size" : 583048,
    "uuid" : "e7a99595-e0f8-34af-be8b-9347d0d658a4",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6883872768,
    "size" : 53248,
    "uuid" : "1f30fb9a-bdf9-32db-a709-8417666a7e45",
    "path" : "\/usr\/lib\/system\/libsystem_pthread.dylib",
    "name" : "libsystem_pthread.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6883635200,
    "size" : 237560,
    "uuid" : "08c5fe2a-b0bf-3ab6-bb42-460c18917d33",
    "path" : "\/usr\/lib\/system\/libsystem_kernel.dylib",
    "name" : "libsystem_kernel.dylib"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7041421312,
    "CFBundleShortVersionString" : "1.0",
    "CFBundleIdentifier" : "com.apple.audio.caulk",
    "size" : 167936,
    "uuid" : "94eafeb1-517c-3d98-8d0d-9c350f0eb986",
    "path" : "\/System\/Library\/PrivateFrameworks\/caulk.framework\/Versions\/A\/caulk",
    "name" : "caulk"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 6918492160,
    "CFBundleShortVersionString" : "5.0",
    "CFBundleIdentifier" : "com.apple.audio.CoreAudio",
    "size" : 6897664,
    "uuid" : "86c35c01-57f0-3e1a-851e-201b9e4f75f9",
    "path" : "\/System\/Library\/Frameworks\/CoreAudio.framework\/Versions\/A\/CoreAudio",
    "name" : "CoreAudio",
    "CFBundleVersion" : "5.0"
  },
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "sharedCache" : {
  "base" : 6879707136,
  "size" : 3553361920,
  "uuid" : "9c875b0a-d532-3933-b1f0-f1ea72cedde2"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=1.2G resident=0K(0%) swapped_out_or_unallocated=1.2G(100%)\nWritable regions: Total=1.5G written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=1.5G(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nActivity Tracing                   256K        1 \nColorSync                          480K       23 \nCoreGraphics                        16K        1 \nFoundation                          16K        1 \nKernel Alloc Once                   32K        1 \nMALLOC                           288.4M       44 \nMALLOC guard page                  192K       10 \nMALLOC_MEDIUM (reserved)         840.0M        7         reserved VM address space (unallocated)\nMALLOC_NANO (reserved)           384.0M        1         reserved VM address space (unallocated)\nSTACK GUARD                       56.1M        9 \nStack                             12.2M        9 \nVM_ALLOCATE                        176K        4 \nVM_ALLOCATE (reserved)              32K        1         reserved VM address space (unallocated)\n__AUTH                             901K      212 \n__AUTH_CONST                      17.7M      394 \n__CTF                               824        1 \n__DATA                            28.3M      382 \n__DATA_CONST                      18.3M      397 \n__DATA_DIRTY                       980K      133 \n__FONT_DATA                        2352        1 \n__LINKEDIT                       807.3M        3 \n__OBJC_RO                         66.4M        1 \n__OBJC_RW                         2012K        1 \n__TEXT                           396.9M      416 \ndyld private memory                272K        2 \nmapped file                       65.5M       13 \nshared memory                     2896K       14 \n===========                     =======  ======= \nTOTAL                              2.9G     2082 \nTOTAL, minus reserved VM space     1.7G     2082 \n",
  "legacyInfo" : {
  "threadTriggered" : {
    "name" : "JUCE Message Thread",
    "queue" : "com.apple.main-thread"
  }
},
  "logWritingSignature" : "6fee8e11fd535be87c472c0e58dee7b6a5171325",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "6425c75e4327780c10cc4252",
      "factorPackIds" : {
        "SIRI_HOME_AUTOMATION_INTENT_SELECTION_CACHE" : "642600a457e7664b1698eb32"
      },
      "deploymentId" : 240000004
    },
    {
      "rolloutId" : "5f72dc58705eff005a46b3a9",
      "factorPackIds" : {

      },
      "deploymentId" : 240000015
    }
  ],
  "experiments" : [
    {
      "treatmentId" : "3a3cf641-8471-4e4e-9ad4-81d0ede970fd",
      "experimentId" : "64a84dae90d82611a0bd7d3d",
      "deploymentId" : 400000010
    },
    {
      "treatmentId" : "a092db1b-c401-44fa-9c54-518b7d69ca61",
      "experimentId" : "64a844035c85000c0f42398a",
      "deploymentId" : 400000019
    }
  ]
}
}

Model: MacBookPro18,1, BootROM 8422.141.2, proc 10:8:2 processors, 16 GB, SMC 
Graphics: Apple M1 Pro, Apple M1 Pro, Built-In
Display: Color LCD, 3456 x 2234 Retina, Main, MirrorOff, Online
Memory Module: LPDDR5, Samsung
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4387), wl0: May 27 2023 01:34:59 version 20.96.31.0.8.7.148 FWID 01-126f2c4c
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: USB31Bus
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.
Thunderbolt Bus: MacBook Pro, Apple Inc.

**Comment by baconpaul** [comment]
Super useful thank you

ii think what is happening is we respond poorly to not being able to open a file, probably documents directory. Surge should ask for that permission but if you say no we probably explode

does your Logic Pro have access to the documents folder in security setting pane?

if that doesn’t make sense I can give some more fulsome debugging info tomorrow, 

and of course if that fixes it we should fix surge and this stack trace would let me do so. I can also try some nightly tweaks to be more resilient if needs be

thank you

**Comment by baconpaul** [comment]
I just merged the last in a series of defensive changes which should fix this I think. Can you sometime after about 2 hours from now try a nightky build and let us know if it scans for you in logic?

thanks so much

**Comment by baconpaul** [comment]
I'm gonna leave this open but bounce it out of the milestone.

**Comment by dsnelson1990** [comment]
Hi there,

Sorry to resurrect this again. I uninstalled and re-installed my favorite plugin and I am still receiving the same issue. . .

**Comment by baconpaul** [comment]
you installed 1.3.1? Did you get a crash log for the version?

**Comment by baconpaul** [comment]
Hmm. So you are running under rosetta but I guess you know that. It also shouldn't crash.

The one thing I can think of is logic doesn't have access to your documents folder and that is causing surge to crash for you. 

What do you see in this settings screen? I can try and turn it off and see if logic surge crashes for me too maybe? 

![Screenshot 2024-02-13 at 12 23 52 PM](https://github.com/surge-synthesizer/surge/assets/13387561/2eaa65ff-ab2e-4e01-81b9-e0d19f19580d)

**Comment by dsnelson1990** [comment]
![Image 2-13-24 at 12 55 PM](https://github.com/surge-synthesizer/surge/assets/145924391/e77707b3-cb17-4168-baa5-26d39c1689a4)

**Comment by baconpaul** [comment]
hmm well that's not it then!

I'll try and make a debugging build for you this week. How strange.

**Comment by baconpaul** [comment]
Do me one favor also

There's a folder `~/Documents/Surge XT/FX Presets`

Leave the folder there but move all the contents from the folder out. Does it start then? Or is that folder empty?

Thanks so much.

**Comment by dsnelson1990** [comment]
Oh my!!! It worked! Thank you so much!!!! Surge XT is by far my favorite synth and I've been lost without it.

**Comment by baconpaul** [comment]
Ahh great.

So if you don't mind: Can you send me the contents which you moved away?

I would love to know what file is crashing it. Even if you have corrupted awfulness we shouldn't explode obviously!

You can just zip them up and attach them here.

**Comment by mkruselj** [comment]
@dsnelson1990 Do you still have the files you've moved away? We'd like to investigate them!

**Comment by mkruselj** [comment]
I guess I'm closing this issue now due to inactivity and no response...
